---
- hosts: localhost
  gather_facts: no
  connection: local
  roles:
     - role: rhelbuild
       # any var that might need to be passed to dependent roles should be defined here
       package_name_for_subrole: vim
       java_version_for_subrole: jre1.8.0_73
